name: parcels
channels:
        - conda-forge
        - defaults
dependencies:
        - python=3.13
        - numpy
        - matplotlib
        - parcels
        - netCDF4
        - xarray
        - plotly
        - ipykernel
        - pillow
        - python-kaleido
        - jupyter
        - prettytable